Update install

diff --git a/{{ cookiecutter.package_name }}/scripts/install b/{{ cookiecutter.package_name }}/scripts/install
--- a/{{ cookiecutter.package_name }}/scripts/install
+++ b/{{ cookiecutter.package_name }}/scripts/install
@@ -19,6 +19,18 @@ else
 fi
 
 # Install the project in editable mode with extras
-$UV venv
-$UV pip install hatch
+if ! command -v hatch > /dev/null 2>&1
+then
+    echo "Hatch not found. Setting up environment and installing hatch..."
+    $UV venv
+
+    $UV pip install hatch
+    echo "Hatch installed into the environment."
+else
+    echo "Hatch found. Proceeding with dependency installation."
+fi
+
+echo "Installing local dependencies..."
 $UV pip install -e ".[testing]"
+
+echo "Script finished."
